# Generated by Django 4.1.3 on 2022-12-23 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('user_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('business', models.CharField(blank=True, max_length=40, null=True)),
                ('best_skill', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('languages', models.CharField(blank=True, max_length=255, null=True)),
                ('employment', models.CharField(blank=True, choices=[('At School', 'At School'), ('Employed', 'Employed'), ('Unemployed', 'Unemployed'), ('Self Employed', 'Self Employed')], max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('first_position', models.CharField(blank=True, max_length=255, null=True)),
                ('first_role', models.CharField(blank=True, max_length=255, null=True)),
                ('first_company', models.CharField(blank=True, max_length=255, null=True)),
                ('first_period', models.CharField(blank=True, max_length=255, null=True)),
                ('first_role_description', models.TextField(blank=True, null=True)),
                ('second_position', models.CharField(blank=True, max_length=255, null=True)),
                ('second_role', models.CharField(blank=True, max_length=255, null=True)),
                ('second_company', models.CharField(blank=True, max_length=255, null=True)),
                ('second_period', models.CharField(blank=True, max_length=255, null=True)),
                ('second_role_description', models.TextField(blank=True, null=True)),
                ('third_position', models.CharField(blank=True, max_length=255, null=True)),
                ('third_role', models.CharField(blank=True, max_length=255, null=True)),
                ('third_company', models.CharField(blank=True, max_length=255, null=True)),
                ('third_period', models.CharField(blank=True, max_length=255, null=True)),
                ('third_role_description', models.TextField(blank=True, null=True)),
                ('fourth_position', models.CharField(blank=True, max_length=255, null=True)),
                ('fourth_role', models.CharField(blank=True, max_length=255, null=True)),
                ('fourth_company', models.CharField(blank=True, max_length=255, null=True)),
                ('fourth_period', models.CharField(blank=True, max_length=255, null=True)),
                ('fourth_role_description', models.TextField(blank=True, null=True)),
                ('fifth_position', models.CharField(blank=True, max_length=255, null=True)),
                ('fifth_role', models.CharField(blank=True, max_length=255, null=True)),
                ('fifth_company', models.CharField(blank=True, max_length=255, null=True)),
                ('fifth_period', models.CharField(blank=True, max_length=255, null=True)),
                ('fifth_role_description', models.TextField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('github', models.CharField(blank=True, max_length=255, null=True)),
                ('tiktok', models.CharField(blank=True, max_length=255, null=True)),
                ('subscribe', models.IntegerField(default=1)),
                ('about_me', models.TextField(blank=True, null=True)),
                ('user_p', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_p', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media')),
                ('project_name', models.CharField(max_length=255)),
                ('clients', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.CharField(blank=True, max_length=40, null=True)),
                ('due_date', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('project_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_owner', to='account.profile')),
            ],
        ),
    ]
