# Generated by Django 4.1.3 on 2022-12-23 23:03

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(default=0, max_length=2555)),
                ('profile_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('privacy', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Private', max_length=255)),
                ('association_type', models.CharField(choices=[('Association', 'Association'), ('Community', 'Community'), ('Company/Business', 'Company/Business'), ('University', 'University'), ('Secondary', 'Secondary')], default='Association', max_length=255)),
                ('school_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('motto', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('youtube', models.CharField(blank=True, max_length=255, null=True)),
                ('slogan', models.CharField(max_length=255)),
                ('currency', models.CharField(blank=True, max_length=255, null=True)),
                ('languages', models.CharField(blank=True, max_length=255, null=True)),
                ('about_us', models.TextField(blank=True, max_length=255, null=True)),
                ('mission', models.CharField(blank=True, max_length=255, null=True)),
                ('vission', models.CharField(blank=True, max_length=255, null=True)),
                ('first_goal', models.CharField(blank=True, max_length=255, null=True)),
                ('second_goal', models.CharField(blank=True, max_length=255, null=True)),
                ('third_goal', models.CharField(blank=True, max_length=255, null=True)),
                ('what_we_do', models.TextField(blank=True, max_length=255, null=True)),
                ('head_office', models.CharField(blank=True, max_length=255, null=True)),
                ('financial_year', models.CharField(max_length=255)),
                ('approved', models.IntegerField(default=1)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founder', to='account.profile')),
            ],
        ),
        migrations.CreateModel(
            name='association_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_status', models.CharField(default='active', max_length=255)),
                ('member_status', models.CharField(default='active', max_length=255)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='account.profile')),
                ('myassociation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myassociation', to='community.association')),
            ],
        ),
        migrations.CreateModel(
            name='association_leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('President', 'President'), ('General Secretary', 'General Secretary'), ('Treasurer', 'Treasurer'), ('Other Position', 'Other Position')], default='President', max_length=255)),
                ('other_position', models.CharField(blank=True, max_length=255, null=True)),
                ('leadership_role', models.CharField(default=1, max_length=255)),
                ('financial_year', models.CharField(blank=True, max_length=255, null=True)),
                ('leader_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Deleted', 'Deleted')], default='active', max_length=255)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('associationleader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associationleader', to='community.association_member')),
            ],
        ),
    ]
