# Generated by Django 4.1.3 on 2022-12-23 23:03

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_assoc1', models.IntegerField(default=0)),
                ('business_assoc2', models.IntegerField(default=0)),
                ('business_assoc3', models.IntegerField(default=0)),
                ('shipping_area', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_fee', models.CharField(blank=True, max_length=255, null=True)),
                ('cover_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media')),
                ('business_name', models.CharField(max_length=255)),
                ('business_address', models.CharField(max_length=255)),
                ('business_slogan', models.CharField(blank=True, max_length=255, null=True)),
                ('business_contacts', models.CharField(max_length=255)),
                ('about_business', models.CharField(max_length=255)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('business_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_owner', to='account.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_brand_name', models.CharField(max_length=255)),
                ('product_generic_name', models.CharField(max_length=255)),
                ('product_packaging', models.CharField(max_length=255)),
                ('product_quantity', models.CharField(max_length=255)),
                ('product_purchase_price', models.DecimalField(decimal_places=1, default=0, max_digits=25)),
                ('product_price', models.DecimalField(decimal_places=1, default=0, max_digits=25)),
                ('product_description', models.TextField()),
                ('product_availability', models.CharField(default='In Stock', max_length=255)),
                ('product_color', models.CharField(blank=True, max_length=255, null=True)),
                ('product_old_price', models.DecimalField(decimal_places=1, default=0, max_digits=25)),
                ('product_category', models.IntegerField(default=0)),
                ('product_type', models.CharField(default='none', max_length=255)),
                ('image1', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media')),
                ('image2', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media')),
                ('image3', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('business_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_p', to='business.business')),
            ],
        ),
        migrations.CreateModel(
            name='Business_Product_Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_category', models.IntegerField(default=0)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('business_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_cat', to='business.business')),
            ],
        ),
    ]
