# Generated by Django 4.1.3 on 2022-12-26 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=1, default=0, max_digits=25)),
                ('total_price', models.DecimalField(decimal_places=1, default=0, max_digits=25)),
                ('total_order_price', models.DecimalField(decimal_places=1, default=0, max_digits=25)),
                ('buyer_status', models.BooleanField(default=False)),
                ('seller_status', models.BooleanField(default=False)),
                ('recieved_status', models.BooleanField(default=False)),
                ('payement_mode', models.CharField(choices=[('Not Paid', 'Not Paid'), ('Cash', 'Cash'), ('Mobile Money', 'Mobile Money'), ('Bank', 'Bank'), ('E-Transfer', 'E-Transfer')], default='Not Paid', max_length=255)),
                ('transaction_id', models.CharField(default='None', max_length=255)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('order_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_by', to='account.profile')),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='business.products')),
            ],
        ),
    ]
