# Generated by Django 4.1.3 on 2022-12-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_no',
            field=models.IntegerField(default=0),
        ),
    ]
