# Generated by Django 4.1.3 on 2022-12-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_remove_orders_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_no',
            field=models.IntegerField(default=0),
        ),
    ]
