# Generated by Django 4.1.3 on 2022-12-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_orders_order_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='payement_mode',
            new_name='order_payement_mode',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='transaction_id',
            new_name='order_transaction_id',
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_paid',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=25),
        ),
    ]
