# Generated by Django 4.1.3 on 2022-12-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_rename_payement_mode_orders_order_payement_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_payement_mode',
            field=models.CharField(choices=[('Not Paid', 'Not Paid'), ('Cash', 'Cash'), ('Mobile Money', 'Mobile Money'), ('Mobile Money and Cash', 'Mobile Money and Cash'), ('Bank', 'Bank'), ('E-Transfer', 'E-Transfer')], default='Not Paid', max_length=255),
        ),
    ]
