# Generated by Django 4.1.3 on 2023-01-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_orders_order_payement_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='balance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=25),
        ),
    ]
