# Generated by Django 4.1.3 on 2022-12-23 23:03

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('comment_likes_count', models.IntegerField(default=0)),
                ('reply_count', models.IntegerField(default=0)),
                ('date_commented', models.DateTimeField(auto_now_add=True)),
                ('comment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_by', to='account.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField()),
                ('post_image1', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media')),
                ('post_image2', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media')),
                ('post_image3', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media')),
                ('likes_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('images', models.IntegerField(default=0)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_by', to='account.profile')),
                ('posted_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_to', to='community.association')),
            ],
        ),
        migrations.CreateModel(
            name='LikedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_liked', models.DateTimeField(auto_now_add=True)),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='account.profile')),
                ('post_liked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_liked', to='feed.posts')),
            ],
        ),
        migrations.CreateModel(
            name='LikedComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_liked', models.DateTimeField(auto_now_add=True)),
                ('comment_liked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_liked', to='feed.comments')),
                ('comment_liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_liked_by', to='account.profile')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_id', to='feed.posts'),
        ),
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('date_replied', models.DateTimeField(auto_now_add=True)),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_id', to='feed.comments')),
                ('reply_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_by', to='account.profile')),
            ],
        ),
    ]
