# Generated by Django 4.1.3 on 2022-12-27 12:42

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support_Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media')),
                ('image2', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media')),
                ('image3', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media')),
                ('account_name', models.CharField(max_length=255)),
                ('call_to_action', models.CharField(max_length=255)),
                ('button_text', models.CharField(max_length=255)),
                ('needed_amount', models.IntegerField(default=0)),
                ('account_status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=255)),
                ('display_total_status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_made', models.DateTimeField(auto_now_add=True)),
                ('support_assoc_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_assoc_by', to='community.association')),
                ('support_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_created_by', to='account.profile')),
            ],
        ),
    ]
