# Generated by Django 4.1.3 on 2022-12-27 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('mysupport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support_Accounts_transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_amount', models.DecimalField(decimal_places=1, default=0, max_digits=25)),
                ('support_paid', models.DecimalField(decimal_places=1, default=0, max_digits=25)),
                ('account_balance', models.DecimalField(decimal_places=1, default=0, max_digits=25)),
                ('payement_mode', models.CharField(choices=[('Not Paid', 'Not Paid'), ('Cash', 'Cash'), ('Mobile Money', 'Mobile Money'), ('Bank', 'Bank'), ('E-Transfer', 'E-Transfer')], default='Not Paid', max_length=255)),
                ('tressurer_confirm', models.CharField(choices=[('Valid', 'Valid'), ('Invalid', 'Invalid')], default='Invalid', max_length=255)),
                ('supporter_confirm', models.CharField(choices=[('Valid', 'Valid'), ('Invalid', 'Invalid')], default='Invalid', max_length=255)),
                ('date_made', models.DateTimeField(auto_now_add=True)),
                ('account_supported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_supported', to='mysupport.support_accounts')),
                ('support_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_by', to='account.profile')),
            ],
        ),
    ]
