# Generated by Django 4.1.3 on 2022-12-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysupport', '0002_support_accounts_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='support_accounts_transactions',
            name='transaction_id',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
