# Generated by Django 4.1.3 on 2022-12-27 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('mysupport', '0003_support_accounts_transactions_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='support_accounts_transactions',
            name='recievied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recievied_by', to='account.profile'),
        ),
    ]
