# Generated by Django 4.1.3 on 2022-12-23 23:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_the_week', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Monday', max_length=255)),
                ('event', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=255)),
                ('date_made', models.DateTimeField(auto_now_add=True)),
                ('timetable_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_by', to='account.profile')),
            ],
        ),
        migrations.CreateModel(
            name='MyCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('event_time', models.CharField(max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('date_made', models.DateTimeField(auto_now_add=True)),
                ('calendar_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_by', to='account.profile')),
            ],
        ),
    ]
